### ISSUE TITLE
Week 4: Peer to peer code review

### ISSUE THREAD

**Issue by kessio** [pratap-panabaka/leaderboard#3]
Hello, @PRATAP-KUMAR 👋🏾, good job on your project 🥇 

Here are some suggestions you can implement from peer review 😸 
- Kindly use overflow-y to prevent you lists from overflowing

**Comment by pratap-panabaka** [comment]
thank you team for your code review, I have implemented the overflow-y.

![image](https://user-images.githubusercontent.com/40719899/187136595-1f818f1d-9019-4e98-958d-ab8d3e041a1a.png)
