### ISSUE TITLE
Peer To Peer Code Review 

### ISSUE THREAD

**Issue by shah-shuja-dev** [pratap-panabaka/leaderboard#5]
## Hello PRATAP 👋🏻 
**Thank you for sharing your code with your morning team. You've done an amazing job with your web application 🎉.Please Take these suggestions listed below and try to implement them as soon as you can to make your code even more amazing 💯**
![UJr](https://user-images.githubusercontent.com/104627775/187854784-f08b71a2-8525-40d9-bffb-212a9df9e035.gif)

### **HIGHLIGHTS**
- Green Lights on Linter ✔️ 
- Amazing use of Git Flow ✔️ 

### **Suggestions**

- [x]  It would be lovely to see your project live via your readme. Please try to add a Live Demo link of your project in the readme.MD.

**Comment by pratap-panabaka** [comment]
hi @shuja-shah 
Thank you for your review and suggestion

I have now uploaded a preview

Thank You
